# Generated by Django 4.0.5 on 2023-08-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
