# Generated by Django 4.0.5 on 2023-08-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_enquiry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.IntegerField()),
                ('age', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
            ],
        ),
    ]
