# Generated by Django 4.0.5 on 2023-08-11 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_enquiry', '0002_userenquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userenquiry',
            old_name='address',
            new_name='password',
        ),
    ]
