# Generated by Django 4.0.5 on 2023-08-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_enquiry', '0003_rename_address_userenquiry_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userenquiry',
            old_name='password',
            new_name='address',
        ),
    ]
