# Generated by Django 4.0.5 on 2023-08-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_enquiry', '0004_rename_password_userenquiry_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userenquiry',
            old_name='address',
            new_name='query',
        ),
        migrations.RemoveField(
            model_name='userenquiry',
            name='age',
        ),
    ]
