# Generated by Django 4.0.5 on 2023-08-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindatabase',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
